export const SEND_MESSAGE = 'SEND_MESSAGE';
export const CONNECT_SOCKET = 'CONNECT_SOCKET';
export const CONFIGURE_SOCKET = 'CONFIGURE_SOCKET';
export const PING_SOCKET = 'PING_SOCKET';
export const LOAD_ROOMS_LIST = 'LOAD_ROOMS_LIST';
export const LOAD_SETTINGS = 'LOAD_SETTINGS';
export const LOAD_ROOM_MESSAGES = 'LOAD_ROOM_MESSAGES';
export const SELECT_ROOM = 'SELECT_ROOM';
export const PROCESS_SOCKET_MESSAGE = 'PROCESS_SOCKET_MESSAGE';
export const OBTAIN_USER_FROM_STORAGE = 'OBTAIN_USER_FROM_STORAGE';
export const DEFINE_USER = 'DEFINE_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const USER_CREATE_ROOM = 'USER_CREATE_ROOM';
export const INIT_ROOMS_LIST = 'INIT_ROOMS_LIST';
export const UPDATE_ROOMS_ORDER_INFO = 'UPDATE_ROOMS_ORDER_INFO';

export default {
  USER: {
    OBTAIN_USER_FROM_STORAGE: 'OBTAIN_USER_FROM_STORAGE',
    DEFINE_USER: 'DEFINE_USER',
    LOGOUT_USER: 'LOGOUT_USER'
  },
  SOCKET: {
    CONNECT_SOCKET: 'CONNECT_SOCKET',
    PING_SOCKET: 'PING_SOCKET',
    CONFIGURE_SOCKET: 'CONFIGURE_SOCKET',
    PROCESS_SOCKET_MESSAGE: 'PROCESS_SOCKET_MESSAGE',
    SEND_MESSAGE: 'SEND_MESSAGE',
  },
  ROOMS: {
    INIT_ROOMS_LIST: 'INIT_ROOMS_LIST',
    LOAD_ROOMS_LIST: 'LOAD_ROOMS_LIST',
    SELECT_ROOM: 'SELECT_ROOM',
    USER_CREATE_ROOM: 'USER_CREATE_ROOM',
    UPDATE_ROOMS_ORDER_INFO: 'UPDATE_ROOMS_ORDER_INFO',
    LOAD_ROOM_MESSAGES: 'LOAD_ROOM_MESSAGES'
  },
  GENERAL: {
    LOAD_SETTINGS: 'LOAD_SETTINGS',
  }
};
